I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 69, in script call
    call scene8_fairy_forest from _call_scene8_fairy_forest # Встреча с троллем
  File "game/script.rpy", line 294, in script
    with pause(0.5)
  File "game/script.rpy", line 294, in <module>
    with pause(0.5)
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 69, in script call
    call scene8_fairy_forest from _call_scene8_fairy_forest # Встреча с троллем
  File "game/script.rpy", line 294, in script
    with pause(0.5)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 294, in <module>
    with pause(0.5)
NameError: name 'pause' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 3.0
Fri Dec 15 22:50:05 2023
