I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 54, in script call
    call scene10_megastore from _call_scene10_megastore # Разговор с магом
  File "game/script.rpy", line 492, in script
    show mag at rigth with moveinbottom
  File "game/script.rpy", line 492, in <module>
    show mag at rigth with moveinbottom
NameError: name 'rigth' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 54, in script call
    call scene10_megastore from _call_scene10_megastore # Разговор с магом
  File "game/script.rpy", line 492, in script
    show mag at rigth with moveinbottom
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 492, in <module>
    show mag at rigth with moveinbottom
NameError: name 'rigth' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 1.0
Mon Dec  4 20:40:45 2023
