I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 49, in script call
    call scene10_megastore
  File "game/script.rpy", line 387, in script
    show henry at le
  File "game/script.rpy", line 387, in <module>
    show henry at le
NameError: name 'le' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 49, in script call
    call scene10_megastore
  File "game/script.rpy", line 387, in script
    show henry at le
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 387, in <module>
    show henry at le
NameError: name 'le' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 1.0
Fri Dec  1 23:07:20 2023
